
THIS_DIR := $(dir $(abspath $(firstword $(MAKEFILE_LIST))))
include Makefile.common

# Separated source dir for cleanliness
SRCDIR = include/

# Files generated by mk_h.py
H_SOURCES = \
$(SRCDIR)codata_2002.h \
$(SRCDIR)codata_2006.h \
$(SRCDIR)codata_2010.h \
$(SRCDIR)codata_2014.h \
$(SRCDIR)codata_2018.h \
$(SRCDIR)codata_2022.h

# Files generated by mk_hpp.py
HPP_SOURCES = $(H_SOURCES:%.h=%.hpp)

# Files generated by mk_f90.py
F90_SOURCES = $(H_SOURCES:%.h=%.f90) $(SRCDIR)mathematical_constants.f90

# Generated sources
GEN_SOURCES = $(H_SOURCES) $(HPP_SOURCES) $(F90_SOURCES)

PC_FILES = $(PKG_NAME).pc

# Targets
all: $(GEN_SOURCES) pkgconfig

clean: pkgconfig_clean
	$(RM) $(GEN_SOURCES)
	$(MAKE) -C examples $@

install: $(GEN_SOURCES) pkgconfig_install
	$(MKDIR_P) $(DESTDIR)$(includedir) $(DESTDIR)$(docdir)
	$(INSTALL_DATA) $(GEN_SOURCES) $(DESTDIR)$(includedir)
	$(INSTALL_DATA) README.md INSTALL.md $(DESTDIR)$(docdir)

installcheck:
	$(MAKE) -C examples PKG_CONFIG_PATH=$(DESTDIR)$(libdir)/pkgconfig clean check

# Grouped targets:
.INTERMEDIATE: h_sources hpp_sources f90_sources
# Sources are order-only targets (don't remake if timestamp changed)
$(H_SOURCES): | h_sources
$(HPP_SOURCES): | hpp_sources
$(F90_SOURCES): | f90_sources

h_sources hpp_sources f90_sources: %_sources:$(THIS_DIR)mk_%.py | $(SRCDIR)
	cd $(SRCDIR) && $(PYTHON) $<

$(SRCDIR):
	$(MKDIR_P) $@

include Makefile.pkgconfig
