
THIS_DIR := $(dir $(abspath $(firstword $(MAKEFILE_LIST))))
include Makefile.common

# Separated source dir for cleanliness
SRCDIR = $(THIS_DIR)include/

# Files generated by mk_fortran.py
FORTRAN_SOURCES = \
$(SRCDIR)mathematical_constants.f90 \
$(SRCDIR)codata_2002.f90 \
$(SRCDIR)codata_2006.f90 \
$(SRCDIR)codata_2010.f90 \
$(SRCDIR)codata_2014.f90 \
$(SRCDIR)codata_2018.f90 \

PC_FILES = $(PKG_NAME).pc

all release: $(FORTRAN_SOURCES) pkgconfig

clean: pkgconfig_clean
	$(RM) $(FORTRAN_SOURCES)

install: $(FORTRAN_SOURCES) pkgconfig_install
	$(MKDIR_P) $(DESTDIR)$(includedir)
	$(INSTALL_DATA) $(FORTRAN_SOURCES) $(DESTDIR)$(includedir)

# Mulitple files generated by single script
$(FORTRAN_SOURCES): fortran_sources
.PHONY: fortran_sources
fortran_sources: | $(SRCDIR)
	cd $(SRCDIR) && $(PYTHON) $(THIS_DIR)mk_fortran.py

$(SRCDIR):
	$(MKDIR_P) $@

include Makefile.pkgconfig
