
THIS_DIR := $(dir $(abspath $(firstword $(MAKEFILE_LIST))))
include Makefile.common

# Separated source dir for cleanliness
SRCDIR = $(THIS_DIR)include/

# Files generated by mk_hpp.py
HPP_SOURCES = \
$(SRCDIR)codata_2002.hpp \
$(SRCDIR)codata_2006.hpp \
$(SRCDIR)codata_2010.hpp \
$(SRCDIR)codata_2014.hpp \
$(SRCDIR)codata_2018.hpp \

# Files generated by mk_f90.py
F90_SOURCES = \
$(SRCDIR)mathematical_constants.f90 \
$(HPP_SOURCES:%.hpp=%.f90)

# Generated sources
GEN_SOURCES = $(HPP_SOURCES) $(F90_SOURCES)

PC_FILES = $(PKG_NAME).pc

# Targets
all release: $(GEN_SOURCES) pkgconfig

clean: pkgconfig_clean
	$(RM) $(GEN_SOURCES)

install: $(GEN_SOURCES) pkgconfig_install
	$(MKDIR_P) $(DESTDIR)$(includedir)
	$(INSTALL_DATA) $(GEN_SOURCES) $(DESTDIR)$(includedir)

installcheck:
	$(MAKE) -C examples PKG_CONFIG_PATH=$(DESTDIR)$(libdir)/pkgconfig clean check

# Mulitple files generated by single script
.NOTPARALLEL: $(HPP_SOURCES) $(F90_SOURCES)
hpp_sources $(HPP_SOURCES): | $(SRCDIR)
	cd $(SRCDIR) && $(PYTHON) $(THIS_DIR)mk_hpp.py

f90_sources $(F90_SOURCES): | $(SRCDIR)
	cd $(SRCDIR) && $(PYTHON) $(THIS_DIR)mk_f90.py

$(SRCDIR):
	$(MKDIR_P) $@

include Makefile.pkgconfig
