PKG_VERSION = 0.2.0
PKG_NAME = fundamental-constants
PKG_FULLNAME = Fundamental Constants

# Boilerplate
prefix = /usr/local
includedir = $(prefix)/include/$(PKG_NAME)
libdir = $(prefix)/lib
datarootdir = $(prefix)/share
docdir = $(datarootdir)/doc/$(PKG_NAME)
MKDIR_P = mkdir -p
RM = rm -f
PYTHON = python
INSTALL = /usr/bin/install -c
INSTALL_DATA = $(INSTALL) -m 644
