PKG_VERSION = 0.1.0
PKG_NAME = fundamental-constants
PKG_FULLNAME = Fundamental Constants

# Boilerplate
prefix = /usr/local
includedir = $(prefix)/include
libdir = $(prefix)/lib
MKDIR_P = mkdir -p
RM = rm -f
PYTHON = python
INSTALL = /usr/bin/install -c
INSTALL_DATA = $(INSTALL) -m 644
