!-------------------------------------------------------------------------------
! mathematical_constants.f90
! Mathematical Constants
! ------------------------------
! These constants are generated by Python's mpmath, with up to 64 digits.
! Generated using mpmath version 1.4.1
!-------------------------------------------------------------------------------

module mathematical_constants
  use, intrinsic :: iso_fortran_env, only: wp => real64
  implicit none
  real(wp), parameter :: M_PI = 3.141592653589793238462643383279502884197169399375105820974944592_wp
end module mathematical_constants
