#!/usr/bin/env python
import re
from pathlib import Path
import mpmath as mp
import scipy.version
import scipy.constants.codata as _cd

def make_f90_sources(output_dir = Path('.')):
    '''Write .f90 source files to an output_dir'''
    ###
    # Write multi-precision math constants
    # they are better than double-limited standard math (which are limited to 14 digits)
    mp.dps = 64  # go for 64 digits
    math_constants = {
        "M_PI": mp.pi(),
        "M_E": mp.e(),
        "M_SQRT2": mp.sqrt(2),
    }

    # Fortran module begins
    module_name = "mathematical_constants"
    output_file = output_dir / "{module_name}.f90".format(module_name=module_name)
    with output_file.open("w") as file:
        print("Writing {}".format(output_file))
        file.write(
            """!-------------------------------------------------------------------------------
! {file_name}
! Mathematical Constants
! ------------------------------
! These constants are generated by Python's mpmath, with up to 64 digits.
! Generated using mpmath version {mpmath_version}
!-------------------------------------------------------------------------------

module {module_name}
  use, intrinsic:: iso_fortran_env, only: wp => real64
  implicit none
""".format(
                file_name=output_file.name, module_name=module_name,
                mpmath_version=mp.__version__
            )
        )  # Traverse mathematical constant name,value pairs
        for name, value in math_constants.items():
            # Fortran named constant definition
            file.write("  real(wp), parameter :: {} = {}_wp\n".format(name, value))
        # Fortran module ends
        file.write("end module {}\n".format(module_name))

    ###
    # Traverse physical constant series
    # Produce a named Fortran module for each
    for module_name, physical_constants in {
        "physical_constants_2002": _cd._physical_constants_2002,
        "physical_constants_2006": _cd._physical_constants_2006,
        "physical_constants_2010": _cd._physical_constants_2010,
        "physical_constants_2014": _cd._physical_constants_2014,
        "physical_constants_2018": _cd._physical_constants_2018,
    }.items():

        # Fortran module begins
        output_file = output_dir / "{module_name}.f90".format(module_name=module_name)

        with output_file.open("w") as file:
            print("Writing {}".format(output_file))
            file.write(
"""!-------------------------------------------------------------------------------
! {file_name}
! Fundamental Physical Constants
! ------------------------------
! These constants are taken from CODATA Recommended Values of the Fundamental
! Physical Constants. https://physics.nist.gov
! Generated using SciPy version {scipy_version}
!-------------------------------------------------------------------------------

module {module_name}
  use, intrinsic:: iso_fortran_env, only: wp => real64
  implicit none
""".format(
                    file_name=output_file.name, module_name=module_name,
                    scipy_version=scipy.version.full_version

                )
            )
            # Traverse physical constant name,value pairs
            for pretty_key, dict_value in physical_constants.items():

                # Flatten pretty long name:
                # replace all non alphanumeric characters by underscores
                name = re.sub(r"[()]", "", pretty_key)  # first omit parentheses
                name = re.sub(r"[^A-z0-9]", "_", name)

                if pretty_key in _cd._obsolete_constants.keys():
                    obsolete = " (obsolete)" if _cd._obsolete_constants[pretty_key] else ""
                else:
                    obsolete = ""

                # Unpack dictionary value items
                value, unit, uncertainty = dict_value

                # Fortran named constant definition
                file.write(
                    "  real(wp), parameter :: {} = {}_wp  ! ({}) {}{}\n".format(name, value, uncertainty, unit, obsolete)
                )

            # Fortran module ends
            file.write("end module {}\n" "".format(module_name))


if __name__ == "__main__":
    make_f90_sources()
